version: 0.0
os: linux

files:
  -source: /
    destination: /home/ec2-user/server

permissions:
  -object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: server_clear.sh
      timeout: 300
      runas: ec-user
  AfterInstall:
    - location: fix_privileges.sh
      timeout: 300
      runas: ec-user
  ApplicationStart:
    - location: server_start.sh
      timeout: 300
      runas: ec-user
  ApplicationStop:
    - location: server_stop.sh
      timeout: 300
      runas: ec-user

