version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk-11
  build:
    commands:
      - echo Build started on `date`
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/server-0.0.1-SNAPSHOT.jar
    - scripts/*.sh
    - appspec.yml